coursera강의 중 deeplearning.ai의 자료를 참고하여 정리하였습니다.

# 1. Python Basics with Numpy 

- 넘알못이지만......Neural Network를 만들때 가장 기본이 되고 핵심이 되는 함수들 몇개가 있다고 합니다. <br/>
np.exp(), np.sum(), np.rand(), np.reshape 등등...<br/>
이 함수들에 대해 알아보고 deeplearning에서 기본이 되는 함수들을 구현해보겠습니다!

## 1) building basic function wiht numpy

### 1.1 - sigmoid function <br/>

$sigmoid(x) = \frac{1}{1+e^{-x}}$

sigmoid function은 위와 같습니다. <br/>
일단 numpy를 사용하지 않고 math 모듈을 사용하여 sigmoid 함수를 만들어 보겠습니다.

In [9]:
# Math 모듈을 이용할 것입니다.
import math

def basic_sigmoid(x) :
    
    #  math.exp(x) = e^x
    s = 1/(1+math.exp(-x))
    
    return s

basic_sigmoid(3)

0.9525741268224334

잘 되죠??? 근데 왜 numpy를 이용할까요?? 아래를 보면 알 수 있습니다.

In [10]:
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: bad operand type for unary -: 'list'

Math 모듈은 벡터 연산이 되지 않습니다. but!!! numpy는 가능!

In [1]:
import numpy as np

x = np.array([1, 2, 3]) # numpy 배열을 만들어 줍니다. numpy연산이 되는 list라 생각하면 됩니다.
print(np.exp(x)) # 결과는 [exp(1), exp(2), exp(3)]

[ 2.71828183  7.3890561  20.08553692]


numpy는 이렇게 성분 각 각에 연산을 해줍니다. <br/>
다른 예시도 보겠습니다.

In [14]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


느낌이 오시죠? 굉장히 편리합니다.

그럼 numpy를 이용하여 아래와 같은 sigmoid 함수를 만들어 보겠습니다. x는 어떤 모양의 행렬이든 상관이 없습니다.

$$   sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [19]:
def sigmoid(x):
    
    # 아까와 크게 달라진 것은 없습니다.
    s = 1/(1+np.exp(-x))
    return s

그럼 다시 한번 이전의 연산을 해보겠습니다.

In [21]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

<br/> 
## 1.2 - Sigmoid gradient
<br/>

쨘! 그럼 sigmoid의 도함수도 구해보겠습니다. <br/>
$$ s'(x) = s(x) * 1-f(x) $$

In [24]:
def sigmoid_derivative(x):

    s = sigmoid(x)
    ds = s*(1-s)

    return ds

In [25]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


<br/>
### 1.3 - Reshaping arrays ###
<br/>

이제 deeplearning에서 흔히 쓰이는 두 함수에 대해 알아보도록 하겠습니다. <br/>
array의 shape를 알아내는 np.shape와 <br/>
array의 shape를 바꾸는 np.reshape()입니다!

In [37]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print(image.shape)
print(image.shape[0], image.shape[1], image.shape[2])

# index는 첫번째가 0입니다.


(3, 3, 2)
3 3 2


shape는 우리가 아는 행렬의 구조와 같습니다.

그럼 이제 image를 행벡터로 바꾸어 보겠습니다. 즉 (1,m)의 배열로 만드는 것입니다.

In [43]:
image_reshaped = image.reshape(((1,image.shape[0] *image.shape[1] *image.shape[2])))
image_reshaped

array([[0.67826139, 0.29380381, 0.90714982, 0.52835647, 0.4215251 ,
        0.45017551, 0.92814219, 0.96677647, 0.85304703, 0.52351845,
        0.19981397, 0.27417313, 0.60659855, 0.00533165, 0.10820313,
        0.49978937, 0.34144279, 0.94630077]])

위는 아래와 같이 다음과 같이 할 수도 있습니다.

In [44]:
image_reshaped = image.reshape((1,-1))
image_reshaped

array([[0.67826139, 0.29380381, 0.90714982, 0.52835647, 0.4215251 ,
        0.45017551, 0.92814219, 0.96677647, 0.85304703, 0.52351845,
        0.19981397, 0.27417313, 0.60659855, 0.00533165, 0.10820313,
        0.49978937, 0.34144279, 0.94630077]])

-1은 짱짱맨입니다. -1이 무엇을 뜻하냐면, 나머지를 뜻합니다! 즉 나머지 구조를 알아서 맞춰주는 것입니다. 

<br/>
### 1.4 - Normalizing rows
<br/>

이제 Normalize 함수에 대해 알아보도록 하겠습니다.

$$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}$$ 라고하면 $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix} $$ axis = 1은 행별로 구한다는 것을 뜻합니다.     $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}$$ <br/>
이를 코드로 구현해 보겠습니다.

In [45]:
def normalizeRows(x):
   
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True )
    
    x = x/x_norm

    return x

x/x_norm 부분은 아래 brodcasting에서 다시 다루도록 하겠습니다.

In [46]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


<br/>
### 1.5 - Broadcasting and the softmax function ####
<br/>

Broadcasting이란 shape를 맞춰주는 것을 뜻합니다. <br/>
예를 들어 shape가 (2, 3)인 array와 (1, 3)인 array를 더할 때, numpy는 자동으로 (1, 3) array를 (2, 3)로 확장하여 연산합니다. <br/>
즉 $$ \begin{bmatrix} 
    1 & 2 & 3 \\
    4 & 5 & 6 \end{bmatrix}  +  \begin{bmatrix} 10 & 20 & 30  \end{bmatrix} = \begin{bmatrix} 
    1 & 2 & 3 \\
    4 & 5 & 6 \end{bmatrix} + \begin{bmatrix} 
    10 & 20 & 30 \\
    10 & 20 & 30 \end{bmatrix} = \begin{bmatrix} 
    11 & 22 & 33 \\
    4 & 5 & 6 \end{bmatrix}$$ <br/> 이 됩니다. <br/>
    
또한 정수를 더하는 것도 마찬가지입니다. 정수는 (1, 1) shape라 생각하면 됩니다. <br/>
    예를 들어 <br/>
    [1, 2] + 10 = [1,2] + [10, 10] = [11,12] 가 됩니다. <br/><br/>
   
   

그럼 softmax 함수에 대해 알아보도록 하겠습니다. <br/>
softmax의 정의는 다음과 같습니다. <br/> 
$$ softmax(x) =  \frac{e^{x}}{\sum_{j}e^{x_{j}}}$$ <br/>
우리는 아래와 같이 배열에서 행별로 softmax 함수를 구해볼 것입니다. <br/>
$$ softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = 
\begin{bmatrix} 
\frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$


In [2]:
def softmax(x):
    #지수를 씌워줍니다.
    x_exp = np.exp(x)
    
    # axis = 1은 행별로 더해주는 것을 뜻합니다.
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    
    # brodcasting되며 element wise로 연산됩니다.
    s = x_exp/x_sum

    return s

In [3]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


<br/>
### 2.1 Calculating of Arrays and Implement the L1 and L2 loss functions
<br/>


배열의 product에 대해 알아보겠습니다. 우리가 알고 있는 행렬의 곱셈, 내적 등과 같습니다.
np.dot() --> 행렬의 곱<br/>
np.inner() --> 행렬의 내적<br/>
np.outer() -->행렬의 외적<br/>
그럼 이것을 이용하여 Loss function을 구해보도록 하겠습니다.

- L1 loss is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}$$

In [6]:
def L1(yhat, y):
   
    # np.abs는 절댓값을 씌워주는 함수입니다.
    loss = np.sum(np.abs(y-yhat))
    
    return loss

In [7]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


 <br/>
 `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 를 이용하여 L2를 구할 것입니다.<br/>
- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}$$

In [8]:
def L2(yhat, y):

    loss = np.dot(y-yhat,y-yhat)
    
    return loss

In [9]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


# 마무리 #

- 다음주에는 binary classification 과제를 정리하여 돌아오겠습니다! 